// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Character struct {
	ID           uuid.UUID
	Name         string
	Description  string
	Class        sql.NullString
	Race         sql.NullString
	Level        sql.NullInt32
	Strengh      sql.NullInt32
	Dexterity    sql.NullInt32
	Constitution sql.NullInt32
	Wisdom       sql.NullInt32
	Intelligence sql.NullInt32
	Charisma     sql.NullInt32
}

type User struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}
