// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const save = `-- name: Save :exec
INSERT INTO
    users (id, username, email, password)
VALUES
    ($1, $2, $3, $4)
`

type SaveParams struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.ExecContext(ctx, save,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	return err
}
